<?php

/**
 * AccountsReceivableBeginningBalanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccountsReceivableBeginningBalanceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccountsReceivableBeginningBalanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AccountsReceivableBeginningBalance');
    }
}