<?php

/**
 * AccountsPayableVoucherAccountEntryOutputVatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccountsPayableVoucherAccountEntryOutputVatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccountsPayableVoucherAccountEntryOutputVatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AccountsPayableVoucherAccountEntryOutputVat');
    }
}