<?php

/**
 * AccountsPayableVoucherTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccountsPayableVoucherTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccountsPayableVoucherTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AccountsPayableVoucher');
    }
}