<?php

/**
 * AccountsPayableBeginningBalanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccountsPayableBeginningBalanceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccountsPayableBeginningBalanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AccountsPayableBeginningBalance');
    }
}