<?php

/**
 * AccountsPayableVoucherParticularEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccountsPayableVoucherParticularEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccountsPayableVoucherParticularEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AccountsPayableVoucherParticularEntry');
    }
}