<?php

/**
 * BankTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BankTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BankTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bank');
    }
}