<?php

/**
 * BankAccountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BankAccountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BankAccountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BankAccount');
    }
}