<?php

/**
 * CashVoucherEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CashVoucherEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CashVoucherEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CashVoucherEntry');
    }
}