<?php

/**
 * ChartOfAccountGroupCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChartOfAccountGroupCodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChartOfAccountGroupCodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChartOfAccountGroupCode');
    }
}