<?php

/**
 * ChartOfAccountTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChartOfAccountTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChartOfAccountTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChartOfAccountType');
    }
	
}