<?php

/**
 * ChartOfAccountType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ChartOfAccountType extends BaseChartOfAccountType
{
	const TYPE_ASSET 	 = "ASSET";
	const TYPE_LIABILITY = "LIABILITY";
	const TYPE_CAPITAL 	 = "CAPITAL";
	const TYPE_INCOME 	 = "INCOME";
	const TYPE_EXPENSE 	 = "EXPENSE";
	
	const ENTRY_TYPE_DEBIT  = "DEBIT";
	const ENTRY_TYPE_CREDIT = "CREDIT";
}