<?php

/**
 * ChartOfAccountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChartOfAccountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChartOfAccountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChartOfAccount');
    }
	
	public function getAccountsByType($type = "ALL", $format)
	{
		$result = $this->createQuery("c")
					   ->leftJoin("c.AccountType at");
		if($type != 'ALL'){ 
			$result->where("at.type = ?",$type);
		} 
		
		
		if($format == 'array'){
			$result = $result->fetchArray();
			$new_result = array();
			foreach($result as $data){
				if($format == 'optionsarray'){
					$new_result[$data->getId()] = $data;
				}else{
					$new_result[$data->getId()] = $data;
				}
			}
			return $new_result;
		}elseif($format == 'optionsarray'){ 
			$result = $result->execute();
			$new_result = array(''=>'');
			foreach($result as $data){ 
				$new_result[$data->getId()] = $data->getAccountType()->getType()." - ". $data->getTitle(); 
			}
			return $new_result;
		}else{
			//do default
		}
		
		return $result = $result->execute();
	}
	 
}