<?php

/**
 * ChartOfAccountTypeValidationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChartOfAccountTypeValidationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChartOfAccountTypeValidationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChartOfAccountTypeValidation');
    }
}