<?php

/**
 * ChartOfAccountValidationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChartOfAccountValidationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChartOfAccountValidationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChartOfAccountValidation');
    }
}