<?php

/**
 * CheckVoucherEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CheckVoucherEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CheckVoucherEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CheckVoucherEntry');
    }
}