<?php

/**
 * CheckVoucher
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CheckVoucher extends BaseCheckVoucher
{

}