<?php

/**
 * ClientTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClientType');
    }
}