<?php

/**
 * CurrencyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CurrencyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CurrencyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Currency');
    }
	
	public function getAllExceptBase($exempt_base = true)
	{
		$result = $this->createQuery("c")
					   ->select("*");
		if($exempt_base){
			$result = $result->where("is_base != ?",true);
		}
		$result = $result->execute();
		return $result;
	}
	
	public function setCurrencyFormat($amount,$currency_id = 0)
	{
		$symbol = Currency::DEFAULT_CURRENCY;
		if($result = $this->createQuery("c")
			          ->select('c.symbol')
			          ->where("c.id = ?",$currency_id)
			          ->execute()
			          ->getFirst()){
			$symbol = $result->getSymbol();		  
		  };
		return $symbol." ".$amount;
	}
}