<?php

/**
 * DebitCreditMemoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DebitCreditMemoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DebitCreditMemoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DebitCreditMemo');
    }
}