<?php

/**
 * DebitCreditMemoAccountEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DebitCreditMemoAccountEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DebitCreditMemoAccountEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DebitCreditMemoAccountEntry');
    }
}