<?php

/**
 * DebitCreditMemoAccountEntryOutputVatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DebitCreditMemoAccountEntryOutputVatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DebitCreditMemoAccountEntryOutputVatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DebitCreditMemoAccountEntryOutputVat');
    }
}