<?php

/**
 * FinancialSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FinancialSettingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FinancialSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FinancialSetting');
    } 
	
	public function getDetails()
	{
		$result = $this->createQuery("f")
					   ->select("*")
					   ->limit(1)
					   ->execute()
					   ->getFirst();
		return $result;
	}
}