<?php

/**
 * GeneralLibraryCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GeneralLibraryCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GeneralLibraryCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GeneralLibraryCategory');
    }
}