<?php

/**
 * GeneralLibraryTermsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GeneralLibraryTermsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GeneralLibraryTermsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GeneralLibraryTerms');
    }
}