<?php

/**
 * GeneralLibraryBillingInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GeneralLibraryBillingInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GeneralLibraryBillingInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GeneralLibraryBillingInfo');
    }
}