<?php

/**
 * GeneralLedgerBeginningBalanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GeneralLedgerBeginningBalanceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GeneralLedgerBeginningBalanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GeneralLedgerBeginningBalance');
    }
}