<?php

/**
 * GroupCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupCodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupCodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupCode');
    }
}