<?php

/**
 * InvoiceAccountEntryOutputVatEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvoiceAccountEntryOutputVatEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InvoiceAccountEntryOutputVatEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InvoiceAccountEntryOutputVatEntry');
    }
}