<?php

/**
 * InvoiceAccountEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvoiceAccountEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InvoiceAccountEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InvoiceAccountEntry');
    }
}