<?php

/**
 * InvoiceParticularEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvoiceParticularEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InvoiceParticularEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InvoiceParticularEntry');
    }
	
	public function getVatApplicationInArray($add_empty = false)
	{
		$vat_applications = array();
		if($add_empty){
			$vat_applications[] = "";
		}
		
		$vat_applications[InvoiceParticularEntry::VAT_EXEMPT] 		= InvoiceParticularEntry::VAT_EXEMPT;
		$vat_applications[InvoiceParticularEntry::VAT_ZERO_PERCENT] = InvoiceParticularEntry::VAT_ZERO_PERCENT;
		$vat_applications[InvoiceParticularEntry::VAT_INCLUSIVE] 	= InvoiceParticularEntry::VAT_INCLUSIVE;
		$vat_applications[InvoiceParticularEntry::VAT_EXCLUSIVE] 	= InvoiceParticularEntry::VAT_EXCLUSIVE;
		
		return $vat_applications;
		
	}
}