<?php

/**
 * JournalVoucherAccountEntryOutputVatEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JournalVoucherAccountEntryOutputVatEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JournalVoucherAccountEntryOutputVatEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JournalVoucherAccountEntryOutputVatEntry');
    }
}