<?php

/**
 * JournalBookBookTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JournalBookBookTemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JournalBookBookTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JournalBookBookTemplate');
    }
}