<?php

/**
 * JournalVoucherParticularEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JournalVoucherParticularEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JournalVoucherParticularEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JournalVoucherParticularEntry');
    }
}