<?php

/**
 * JournalBookTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class JournalBookTemplate extends BaseJournalBookTemplate
{
	const ENTRY_TYPE_DEBIT  = "DEBIT";
	const ENTRY_TYPE_CREDIT = "CREDIT";
	
	public function getValueByEntryType()
	{
		$value = $this->getCredit();
		
		if($this->getChartOfAccount()->getEntryType() == self::ENTRY_TYPE_DEBIT){		
			return $this->getDebit();
		}		
		return $value;
	}
}