<?php

/**
 * JournalVoucherAccountEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JournalVoucherAccountEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JournalVoucherAccountEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JournalVoucherAccountEntry');
    }
}