<?php

/**
 * JournalBookParticularTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JournalBookParticularTemplateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JournalBookParticularTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JournalBookParticularTemplate');
    }
}