<?php

/**
 * JournalBookTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JournalBookTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JournalBookTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JournalBook');
    }
}