<?php

/**
 * OrganizationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganizationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrganizationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Organization');
    }
	
	public function getDetails()
	{
		$result = $this->createQuery("o")
					   ->select("*")
					   ->limit(1)
					   ->execute()
					   ->getFirst();
		return $result;
	}
	
	public static function getDisplayName()
	{
		if($result = self::getInstance()->createQuery("o")->execute()->getFirst()){
			return $result->getDisplayName();
		}
		
		return '';
	}
}