<?php

/**
 * OrganizationTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganizationTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrganizationTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrganizationType');
    }
}