<?php

/**
 * ParticularTemplateEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParticularTemplateEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParticularTemplateEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ParticularTemplateEntry');
    }
}