<?php

/**
 * PettyCashVoucherParticularEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PettyCashVoucherParticularEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PettyCashVoucherParticularEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PettyCashVoucherParticularEntry');
    }
}