<?php

/**
 * PettyCashVoucherAccountEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PettyCashVoucherAccountEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PettyCashVoucherAccountEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PettyCashVoucherAccountEntry');
    }
}