<?php

/**
 * PettyCashVoucherAccountEntryOutputVatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PettyCashVoucherAccountEntryOutputVatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PettyCashVoucherAccountEntryOutputVatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PettyCashVoucherAccountEntryOutputVat');
    }
}