<?php

/**
 * PrepaymentAccountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrepaymentAccountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrepaymentAccountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PrepaymentAccount');
    }
}