<?php

/**
 * ReceiptCheckEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReceiptCheckEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReceiptCheckEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReceiptCheckEntry');
    }
}