<?php

/**
 * ReceiptAccountEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReceiptAccountEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReceiptAccountEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReceiptAccountEntry');
    }
}