<?php

/**
 * ReceiptAccountEntryOutputVatEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReceiptAccountEntryOutputVatEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReceiptAccountEntryOutputVatEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReceiptAccountEntryOutputVatEntry');
    }
}