<?php

/**
 * ReceiptParticularEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReceiptParticularEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReceiptParticularEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReceiptParticularEntry');
    }
	
	public function getVatApplicationInArray($add_empty = false)
	{
		$vat_applications = array();
		if($add_empty){
			$vat_applications[] = "";
		}
		
		$vat_applications[ReceiptParticularEntry::VAT_EXEMPT] 		= ReceiptParticularEntry::VAT_EXEMPT;
		$vat_applications[ReceiptParticularEntry::VAT_ZERO_PERCENT] = ReceiptParticularEntry::VAT_ZERO_PERCENT;
		$vat_applications[ReceiptParticularEntry::VAT_INCLUSIVE] 	= ReceiptParticularEntry::VAT_INCLUSIVE;
		$vat_applications[ReceiptParticularEntry::VAT_EXCLUSIVE] 	= ReceiptParticularEntry::VAT_EXCLUSIVE;
		
		return $vat_applications;
		
	}
}