<?php

/**
 * ReceiptCashEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReceiptCashEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReceiptCashEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReceiptCashEntry');
    }
}