<?php

/**
 * ReceiptAccountEntryOutputVatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReceiptAccountEntryOutputVatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReceiptAccountEntryOutputVatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReceiptAccountEntryOutputVat');
    }
}