<?php

/**
 * RolePrivilegeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RolePrivilegeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RolePrivilegeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RolePrivilege');
    }
}