<?php

/**
 * RolePrivilegesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RolePrivilegesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RolePrivilegesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RolePrivileges');
    }
}