<?php

/**
 * TaxClassTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxClassTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxClassTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaxClass');
    }
}