<?php

/**
 * TaxFinalWithheldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxFinalWithheldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxFinalWithheldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaxFinalWithheld');
    }
}