<?php

/**
 * TaxRateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxRateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxRateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaxRate');
    }
	
	public function getCurrenttaxRate()
	{
		$default_rate = 12.5;
		$current_date = date("y-m-d");
		$result  = $this->createQuery()
						->select('rate')
						->where('effectivity_date >= ?',$current_date)
						->execute()
						->getFirst();
	   if($result){
		return $result->getNewRate();
	   }
	   return $default_rate;
	}
}