<?php

/**
 * TermsOfPaymentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TermsOfPaymentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TermsOfPaymentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TermsOfPayment');
    }
}