<?php

/**
 * UserPositionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserPositionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserPositionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserPositions');
    }
}