<?php

/**
 * UserRolesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserRolesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserRolesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserRoles');
    }
}