<?php

/**
 * UserStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserStatus');
    }
}