TaxClass:
    actAs: { Timestampable: ~ }
    columns:
        code:  { type: string(50), notnull: true, default: '', unique: true }
        title:  { type: string(60), notnull:true, default: '' }
        description:  { type: string }
        tax_rate_percent: { type: decimal(4), scale:2 }