Organization:
    actAs: { Timestampable: ~ }
    columns:
        display_name:  { type: string(50), notnull: true, default: ''}
        legal_name:  { type: string(100), notnull: true, default: ''}
        organization_type_id:  { type: int(11) }  
        rdo_code:  { type: string(10) } 
        branch_code:  { type: string(10) } 
        tin:  { type: string(12) } 
        logo:  { type: string(150) } 
        street:  { type: string } 
        city:  { type: string(100) }   
        code:  { type: int(11) } 
        country_id:  { type: int(11) }  
        telephone_number:  { type: string(60) }  
        fax:  { type: string(60) }  
        mobile_number:  { type: string(50) }   
        email:  { type: string(60) }   
        facebook_url:  { type: string(150) }   
        twitter_url:  { type: string(150) }   
        linkedln_url:  { type: string(150) }   
        googleplus_url:  { type: string(150) }
    relations:
        OrganizationType:
            local: organization_type_id
            foreign: id
            onDelete: SET NULL
        Country:
            local: country_id
            foreign: id
            onDelete: SET NULL

OrganizationType:
    actAs: { Timestampable: ~ }
    columns:
        title:  { type: string(60), notnull: true, default: ''} 
        description:  { type: string }