<?php

/**
 * BaseBankAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property int $bank_id
 * @property string $account_name
 * @property string $account_number
 * @property int $currency_id
 * @property boolean $status
 * @property Bank $Bank
 * 
 * @method string      getCode()           Returns the current record's "code" value
 * @method int         getBankId()         Returns the current record's "bank_id" value
 * @method string      getAccountName()    Returns the current record's "account_name" value
 * @method string      getAccountNumber()  Returns the current record's "account_number" value
 * @method int         getCurrencyId()     Returns the current record's "currency_id" value
 * @method boolean     getStatus()         Returns the current record's "status" value
 * @method Bank        getBank()           Returns the current record's "Bank" value
 * @method BankAccount setCode()           Sets the current record's "code" value
 * @method BankAccount setBankId()         Sets the current record's "bank_id" value
 * @method BankAccount setAccountName()    Sets the current record's "account_name" value
 * @method BankAccount setAccountNumber()  Sets the current record's "account_number" value
 * @method BankAccount setCurrencyId()     Sets the current record's "currency_id" value
 * @method BankAccount setStatus()         Sets the current record's "status" value
 * @method BankAccount setBank()           Sets the current record's "Bank" value
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBankAccount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bank_account');
        $this->hasColumn('code', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 10,
             ));
        $this->hasColumn('bank_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('account_name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 50,
             ));
        $this->hasColumn('account_number', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('currency_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Bank', array(
             'local' => 'bank_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}