<?php

/**
 * BaseCountry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $name
 * @property Doctrine_Collection $GeneralLibrary
 * @property GeneralLibraryBillingInfo $GeneralLibraryBillingInfo
 * @property Doctrine_Collection $Organization
 * 
 * @method string                    getCode()                      Returns the current record's "code" value
 * @method string                    getName()                      Returns the current record's "name" value
 * @method Doctrine_Collection       getGeneralLibrary()            Returns the current record's "GeneralLibrary" collection
 * @method GeneralLibraryBillingInfo getGeneralLibraryBillingInfo() Returns the current record's "GeneralLibraryBillingInfo" value
 * @method Doctrine_Collection       getOrganization()              Returns the current record's "Organization" collection
 * @method Country                   setCode()                      Sets the current record's "code" value
 * @method Country                   setName()                      Sets the current record's "name" value
 * @method Country                   setGeneralLibrary()            Sets the current record's "GeneralLibrary" collection
 * @method Country                   setGeneralLibraryBillingInfo() Sets the current record's "GeneralLibraryBillingInfo" value
 * @method Country                   setOrganization()              Sets the current record's "Organization" collection
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCountry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('country');
        $this->hasColumn('code', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GeneralLibrary', array(
             'local' => 'id',
             'foreign' => 'country_id'));

        $this->hasOne('GeneralLibraryBillingInfo', array(
             'local' => 'id',
             'foreign' => 'country_id'));

        $this->hasMany('Organization', array(
             'local' => 'id',
             'foreign' => 'country_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}