<?php

/**
 * BaseDebitCreditMemoAccountEntryOutputVat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $debit_credit_memo_number
 * @property int $chart_of_account_id
 * @property int $general_library_id
 * @property string $tin_number
 * @property ChartOfAccount $ChartOfAccount
 * @property GeneralLibrary $GeneralLibrary
 * @property Doctrine_Collection $DebitCreditMemoAccountEntryOutputVatEntry
 * 
 * @method int                                  getDebitCreditMemoNumber()                     Returns the current record's "debit_credit_memo_number" value
 * @method int                                  getChartOfAccountId()                          Returns the current record's "chart_of_account_id" value
 * @method int                                  getGeneralLibraryId()                          Returns the current record's "general_library_id" value
 * @method string                               getTinNumber()                                 Returns the current record's "tin_number" value
 * @method ChartOfAccount                       getChartOfAccount()                            Returns the current record's "ChartOfAccount" value
 * @method GeneralLibrary                       getGeneralLibrary()                            Returns the current record's "GeneralLibrary" value
 * @method Doctrine_Collection                  getDebitCreditMemoAccountEntryOutputVatEntry() Returns the current record's "DebitCreditMemoAccountEntryOutputVatEntry" collection
 * @method DebitCreditMemoAccountEntryOutputVat setDebitCreditMemoNumber()                     Sets the current record's "debit_credit_memo_number" value
 * @method DebitCreditMemoAccountEntryOutputVat setChartOfAccountId()                          Sets the current record's "chart_of_account_id" value
 * @method DebitCreditMemoAccountEntryOutputVat setGeneralLibraryId()                          Sets the current record's "general_library_id" value
 * @method DebitCreditMemoAccountEntryOutputVat setTinNumber()                                 Sets the current record's "tin_number" value
 * @method DebitCreditMemoAccountEntryOutputVat setChartOfAccount()                            Sets the current record's "ChartOfAccount" value
 * @method DebitCreditMemoAccountEntryOutputVat setGeneralLibrary()                            Sets the current record's "GeneralLibrary" value
 * @method DebitCreditMemoAccountEntryOutputVat setDebitCreditMemoAccountEntryOutputVatEntry() Sets the current record's "DebitCreditMemoAccountEntryOutputVatEntry" collection
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDebitCreditMemoAccountEntryOutputVat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('debit_credit_memo_account_entry_output_vat');
        $this->hasColumn('debit_credit_memo_number', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('chart_of_account_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('general_library_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('tin_number', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ChartOfAccount', array(
             'local' => 'chart_of_account_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('GeneralLibrary', array(
             'local' => 'general_library_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('DebitCreditMemoAccountEntryOutputVatEntry', array(
             'local' => 'id',
             'foreign' => 'debit_credit_memo_account_entry_output_vat_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}