<?php

/**
 * BaseTaxClass
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $title
 * @property string $description
 * @property decimal $tax_rate_percent
 * 
 * @method string   getCode()             Returns the current record's "code" value
 * @method string   getTitle()            Returns the current record's "title" value
 * @method string   getDescription()      Returns the current record's "description" value
 * @method decimal  getTaxRatePercent()   Returns the current record's "tax_rate_percent" value
 * @method TaxClass setCode()             Sets the current record's "code" value
 * @method TaxClass setTitle()            Sets the current record's "title" value
 * @method TaxClass setDescription()      Sets the current record's "description" value
 * @method TaxClass setTaxRatePercent()   Sets the current record's "tax_rate_percent" value
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaxClass extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tax_class');
        $this->hasColumn('code', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 60,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('tax_rate_percent', 'decimal', 4, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}