<?php

/**
 * BaseOrganizationType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property Doctrine_Collection $Organization
 * 
 * @method string              getTitle()        Returns the current record's "title" value
 * @method string              getDescription()  Returns the current record's "description" value
 * @method Doctrine_Collection getOrganization() Returns the current record's "Organization" collection
 * @method OrganizationType    setTitle()        Sets the current record's "title" value
 * @method OrganizationType    setDescription()  Sets the current record's "description" value
 * @method OrganizationType    setOrganization() Sets the current record's "Organization" collection
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrganizationType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('organization_type');
        $this->hasColumn('title', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 60,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Organization', array(
             'local' => 'id',
             'foreign' => 'organization_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}