<?php

/**
 * BaseReceiptAccountEntry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $receipt_id
 * @property int $chart_of_account_id
 * @property int $general_library_id
 * @property string $dn_reference
 * @property decimal $debit
 * @property decimal $credit
 * @property Receipt $Receipt
 * @property ChartOfAccount $ChartOfAccount
 * @property GeneralLibrary $GeneralLibrary
 * 
 * @method int                 getReceiptId()           Returns the current record's "receipt_id" value
 * @method int                 getChartOfAccountId()    Returns the current record's "chart_of_account_id" value
 * @method int                 getGeneralLibraryId()    Returns the current record's "general_library_id" value
 * @method string              getDnReference()         Returns the current record's "dn_reference" value
 * @method decimal             getDebit()               Returns the current record's "debit" value
 * @method decimal             getCredit()              Returns the current record's "credit" value
 * @method Receipt             getReceipt()             Returns the current record's "Receipt" value
 * @method ChartOfAccount      getChartOfAccount()      Returns the current record's "ChartOfAccount" value
 * @method GeneralLibrary      getGeneralLibrary()      Returns the current record's "GeneralLibrary" value
 * @method ReceiptAccountEntry setReceiptId()           Sets the current record's "receipt_id" value
 * @method ReceiptAccountEntry setChartOfAccountId()    Sets the current record's "chart_of_account_id" value
 * @method ReceiptAccountEntry setGeneralLibraryId()    Sets the current record's "general_library_id" value
 * @method ReceiptAccountEntry setDnReference()         Sets the current record's "dn_reference" value
 * @method ReceiptAccountEntry setDebit()               Sets the current record's "debit" value
 * @method ReceiptAccountEntry setCredit()              Sets the current record's "credit" value
 * @method ReceiptAccountEntry setReceipt()             Sets the current record's "Receipt" value
 * @method ReceiptAccountEntry setChartOfAccount()      Sets the current record's "ChartOfAccount" value
 * @method ReceiptAccountEntry setGeneralLibrary()      Sets the current record's "GeneralLibrary" value
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReceiptAccountEntry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('receipt_account_entry');
        $this->hasColumn('receipt_id', 'int', 11, array(
             'type' => 'int',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('chart_of_account_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('general_library_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('dn_reference', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('debit', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'default' => 0,
             'notnull' => true,
             'length' => 12,
             ));
        $this->hasColumn('credit', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'default' => 0,
             'notnull' => true,
             'length' => 12,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Receipt', array(
             'local' => 'receipt_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ChartOfAccount', array(
             'local' => 'chart_of_account_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('GeneralLibrary', array(
             'local' => 'general_library_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}