<?php

/**
 * BaseRolePrivileges
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $role_id
 * @property string $name
 * @property string $description
 * 
 * @method string         getRoleId()      Returns the current record's "role_id" value
 * @method string         getName()        Returns the current record's "name" value
 * @method string         getDescription() Returns the current record's "description" value
 * @method RolePrivileges setRoleId()      Sets the current record's "role_id" value
 * @method RolePrivileges setName()        Sets the current record's "name" value
 * @method RolePrivileges setDescription() Sets the current record's "description" value
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRolePrivileges extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('role_privileges');
        $this->hasColumn('role_id', 'string', 3, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'PHP',
             'unique' => true,
             'length' => 3,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}