<?php

/**
 * BaseGeneralLibraryTerms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property int $term_value
 * @property int $actual_value
 * @property string $description
 * @property GeneralLibraryAdditionInfo $GeneralLibraryAdditionInfo
 * 
 * @method string                     getName()                       Returns the current record's "name" value
 * @method int                        getTermValue()                  Returns the current record's "term_value" value
 * @method int                        getActualValue()                Returns the current record's "actual_value" value
 * @method string                     getDescription()                Returns the current record's "description" value
 * @method GeneralLibraryAdditionInfo getGeneralLibraryAdditionInfo() Returns the current record's "GeneralLibraryAdditionInfo" value
 * @method GeneralLibraryTerms        setName()                       Sets the current record's "name" value
 * @method GeneralLibraryTerms        setTermValue()                  Sets the current record's "term_value" value
 * @method GeneralLibraryTerms        setActualValue()                Sets the current record's "actual_value" value
 * @method GeneralLibraryTerms        setDescription()                Sets the current record's "description" value
 * @method GeneralLibraryTerms        setGeneralLibraryAdditionInfo() Sets the current record's "GeneralLibraryAdditionInfo" value
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGeneralLibraryTerms extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('general_library_terms');
        $this->hasColumn('name', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 60,
             ));
        $this->hasColumn('term_value', 'int', 11, array(
             'type' => 'int',
             'notnull' => true,
             'default' => 0,
             'length' => 11,
             ));
        $this->hasColumn('actual_value', 'int', 11, array(
             'type' => 'int',
             'notnull' => true,
             'default' => 0,
             'length' => 11,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GeneralLibraryAdditionInfo', array(
             'local' => 'id',
             'foreign' => 'term_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}