<?php

/**
 * BaseJournalVoucherAccountEntryOutputVat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $journal_voucher_number
 * @property int $chart_of_account_id
 * @property int $general_library_id
 * @property string $tin_number
 * @property ChartOfAccount $ChartOfAccount
 * @property GeneralLibrary $GeneralLibrary
 * @property Doctrine_Collection $JournalVoucherAccountEntryOutputVatEntry
 * 
 * @method int                                 getJournalVoucherNumber()                     Returns the current record's "journal_voucher_number" value
 * @method int                                 getChartOfAccountId()                         Returns the current record's "chart_of_account_id" value
 * @method int                                 getGeneralLibraryId()                         Returns the current record's "general_library_id" value
 * @method string                              getTinNumber()                                Returns the current record's "tin_number" value
 * @method ChartOfAccount                      getChartOfAccount()                           Returns the current record's "ChartOfAccount" value
 * @method GeneralLibrary                      getGeneralLibrary()                           Returns the current record's "GeneralLibrary" value
 * @method Doctrine_Collection                 getJournalVoucherAccountEntryOutputVatEntry() Returns the current record's "JournalVoucherAccountEntryOutputVatEntry" collection
 * @method JournalVoucherAccountEntryOutputVat setJournalVoucherNumber()                     Sets the current record's "journal_voucher_number" value
 * @method JournalVoucherAccountEntryOutputVat setChartOfAccountId()                         Sets the current record's "chart_of_account_id" value
 * @method JournalVoucherAccountEntryOutputVat setGeneralLibraryId()                         Sets the current record's "general_library_id" value
 * @method JournalVoucherAccountEntryOutputVat setTinNumber()                                Sets the current record's "tin_number" value
 * @method JournalVoucherAccountEntryOutputVat setChartOfAccount()                           Sets the current record's "ChartOfAccount" value
 * @method JournalVoucherAccountEntryOutputVat setGeneralLibrary()                           Sets the current record's "GeneralLibrary" value
 * @method JournalVoucherAccountEntryOutputVat setJournalVoucherAccountEntryOutputVatEntry() Sets the current record's "JournalVoucherAccountEntryOutputVatEntry" collection
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJournalVoucherAccountEntryOutputVat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('journal_voucher_account_entry_output_vat');
        $this->hasColumn('journal_voucher_number', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('chart_of_account_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('general_library_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('tin_number', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ChartOfAccount', array(
             'local' => 'chart_of_account_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('GeneralLibrary', array(
             'local' => 'general_library_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('JournalVoucherAccountEntryOutputVatEntry', array(
             'local' => 'id',
             'foreign' => 'journal_voucher_account_entry_output_vat_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}