<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Users', 'doctrine');

/**
 * BaseUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property string $first_name
 * @property string $last_name
 * @property string $middle_name
 * @property string $username
 * @property string $password
 * @property string $email
 * @property string $picture
 * @property integer $position_id
 * @property integer $role_id
 * @property integer $is_active
 * @property integer $status_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property UserPositions $UserPositions
 * @property UserRoles $UserRoles
 * @property UserStatus $UserStatus
 * 
 * @method integer       getId()            Returns the current record's "id" value
 * @method string        getCode()          Returns the current record's "code" value
 * @method string        getFirstName()     Returns the current record's "first_name" value
 * @method string        getLastName()      Returns the current record's "last_name" value
 * @method string        getMiddleName()    Returns the current record's "middle_name" value
 * @method string        getUsername()      Returns the current record's "username" value
 * @method string        getPassword()      Returns the current record's "password" value
 * @method string        getEmail()         Returns the current record's "email" value
 * @method string        getPicture()       Returns the current record's "picture" value
 * @method integer       getPositionId()    Returns the current record's "position_id" value
 * @method integer       getRoleId()        Returns the current record's "role_id" value
 * @method integer       getIsActive()      Returns the current record's "is_active" value
 * @method integer       getStatusId()      Returns the current record's "status_id" value
 * @method timestamp     getCreatedAt()     Returns the current record's "created_at" value
 * @method timestamp     getUpdatedAt()     Returns the current record's "updated_at" value
 * @method UserPositions getUserPositions() Returns the current record's "UserPositions" value
 * @method UserRoles     getUserRoles()     Returns the current record's "UserRoles" value
 * @method UserStatus    getUserStatus()    Returns the current record's "UserStatus" value
 * @method Users         setId()            Sets the current record's "id" value
 * @method Users         setCode()          Sets the current record's "code" value
 * @method Users         setFirstName()     Sets the current record's "first_name" value
 * @method Users         setLastName()      Sets the current record's "last_name" value
 * @method Users         setMiddleName()    Sets the current record's "middle_name" value
 * @method Users         setUsername()      Sets the current record's "username" value
 * @method Users         setPassword()      Sets the current record's "password" value
 * @method Users         setEmail()         Sets the current record's "email" value
 * @method Users         setPicture()       Sets the current record's "picture" value
 * @method Users         setPositionId()    Sets the current record's "position_id" value
 * @method Users         setRoleId()        Sets the current record's "role_id" value
 * @method Users         setIsActive()      Sets the current record's "is_active" value
 * @method Users         setStatusId()      Sets the current record's "status_id" value
 * @method Users         setCreatedAt()     Sets the current record's "created_at" value
 * @method Users         setUpdatedAt()     Sets the current record's "updated_at" value
 * @method Users         setUserPositions() Sets the current record's "UserPositions" value
 * @method Users         setUserRoles()     Sets the current record's "UserRoles" value
 * @method Users         setUserStatus()    Sets the current record's "UserStatus" value
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('users');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'USR',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('first_name', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('last_name', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('middle_name', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('username', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('picture', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('position_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('role_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('status_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UserPositions', array(
             'local' => 'position_id',
             'foreign' => 'id'));

        $this->hasOne('UserRoles', array(
             'local' => 'role_id',
             'foreign' => 'id'));

        $this->hasOne('UserStatus', array(
             'local' => 'status_id',
             'foreign' => 'id'));
    }
}