<?php

/**
 * BaseInvoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $book_id
 * @property enum $status
 * @property string $invoice_number
 * @property int $general_library_id
 * @property int $currency_id
 * @property string $purchase_order_number
 * @property date $date_receive
 * @property date $period
 * @property int $terms_of_payment_id
 * @property date $due_date
 * @property string $header_message
 * @property string $footer_message
 * @property decimal $total_amount
 * @property Book $Book
 * @property GeneralLibrary $GeneralLibrary
 * @property Currency $Currency
 * @property TermsOfPayment $TermsOfPayment
 * @property Doctrine_Collection $InvoiceParticularEntry
 * @property Doctrine_Collection $InvoiceAccountEntry
 * 
 * @method int                 getBookId()                 Returns the current record's "book_id" value
 * @method enum                getStatus()                 Returns the current record's "status" value
 * @method string              getInvoiceNumber()          Returns the current record's "invoice_number" value
 * @method int                 getGeneralLibraryId()       Returns the current record's "general_library_id" value
 * @method int                 getCurrencyId()             Returns the current record's "currency_id" value
 * @method string              getPurchaseOrderNumber()    Returns the current record's "purchase_order_number" value
 * @method date                getDateReceive()            Returns the current record's "date_receive" value
 * @method date                getPeriod()                 Returns the current record's "period" value
 * @method int                 getTermsOfPaymentId()       Returns the current record's "terms_of_payment_id" value
 * @method date                getDueDate()                Returns the current record's "due_date" value
 * @method string              getHeaderMessage()          Returns the current record's "header_message" value
 * @method string              getFooterMessage()          Returns the current record's "footer_message" value
 * @method decimal             getTotalAmount()            Returns the current record's "total_amount" value
 * @method Book                getBook()                   Returns the current record's "Book" value
 * @method GeneralLibrary      getGeneralLibrary()         Returns the current record's "GeneralLibrary" value
 * @method Currency            getCurrency()               Returns the current record's "Currency" value
 * @method TermsOfPayment      getTermsOfPayment()         Returns the current record's "TermsOfPayment" value
 * @method Doctrine_Collection getInvoiceParticularEntry() Returns the current record's "InvoiceParticularEntry" collection
 * @method Doctrine_Collection getInvoiceAccountEntry()    Returns the current record's "InvoiceAccountEntry" collection
 * @method Invoice             setBookId()                 Sets the current record's "book_id" value
 * @method Invoice             setStatus()                 Sets the current record's "status" value
 * @method Invoice             setInvoiceNumber()          Sets the current record's "invoice_number" value
 * @method Invoice             setGeneralLibraryId()       Sets the current record's "general_library_id" value
 * @method Invoice             setCurrencyId()             Sets the current record's "currency_id" value
 * @method Invoice             setPurchaseOrderNumber()    Sets the current record's "purchase_order_number" value
 * @method Invoice             setDateReceive()            Sets the current record's "date_receive" value
 * @method Invoice             setPeriod()                 Sets the current record's "period" value
 * @method Invoice             setTermsOfPaymentId()       Sets the current record's "terms_of_payment_id" value
 * @method Invoice             setDueDate()                Sets the current record's "due_date" value
 * @method Invoice             setHeaderMessage()          Sets the current record's "header_message" value
 * @method Invoice             setFooterMessage()          Sets the current record's "footer_message" value
 * @method Invoice             setTotalAmount()            Sets the current record's "total_amount" value
 * @method Invoice             setBook()                   Sets the current record's "Book" value
 * @method Invoice             setGeneralLibrary()         Sets the current record's "GeneralLibrary" value
 * @method Invoice             setCurrency()               Sets the current record's "Currency" value
 * @method Invoice             setTermsOfPayment()         Sets the current record's "TermsOfPayment" value
 * @method Invoice             setInvoiceParticularEntry() Sets the current record's "InvoiceParticularEntry" collection
 * @method Invoice             setInvoiceAccountEntry()    Sets the current record's "InvoiceAccountEntry" collection
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInvoice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('invoice');
        $this->hasColumn('book_id', 'int', 11, array(
             'type' => 'int',
             'notnull' => true,
             'default' => '0',
             'length' => 11,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'UNPAID',
              1 => 'PAID',
              2 => 'DUE',
              3 => 'OVERDUE',
             ),
             'default' => 'UNPAID',
             ));
        $this->hasColumn('invoice_number', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('general_library_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('currency_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('purchase_order_number', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('date_receive', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('period', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('terms_of_payment_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('due_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('header_message', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('footer_message', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('total_amount', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'default' => 0,
             'notnull' => true,
             'length' => 12,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Book', array(
             'local' => 'book_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('GeneralLibrary', array(
             'local' => 'general_library_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Currency', array(
             'local' => 'currency_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('TermsOfPayment', array(
             'local' => 'terms_of_payment_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('InvoiceParticularEntry', array(
             'local' => 'id',
             'foreign' => 'invoice_id'));

        $this->hasMany('InvoiceAccountEntry', array(
             'local' => 'id',
             'foreign' => 'invoice_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}