<?php

/**
 * BaseJournalBookBookTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $journal_book_id
 * @property integer $journal_book_template_id
 * @property JournalBook $JournalBook
 * @property JournalBookTemplate $JournalBookTemplate
 * 
 * @method integer                 getJournalBookId()            Returns the current record's "journal_book_id" value
 * @method integer                 getJournalBookTemplateId()    Returns the current record's "journal_book_template_id" value
 * @method JournalBook             getJournalBook()              Returns the current record's "JournalBook" value
 * @method JournalBookTemplate     getJournalBookTemplate()      Returns the current record's "JournalBookTemplate" value
 * @method JournalBookBookTemplate setJournalBookId()            Sets the current record's "journal_book_id" value
 * @method JournalBookBookTemplate setJournalBookTemplateId()    Sets the current record's "journal_book_template_id" value
 * @method JournalBookBookTemplate setJournalBook()              Sets the current record's "JournalBook" value
 * @method JournalBookBookTemplate setJournalBookTemplate()      Sets the current record's "JournalBookTemplate" value
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJournalBookBookTemplate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('journal_book_book_template');
        $this->hasColumn('journal_book_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '',
             'length' => 11,
             ));
        $this->hasColumn('journal_book_template_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '',
             'length' => 11,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('JournalBook', array(
             'local' => 'journal_book_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('JournalBookTemplate', array(
             'local' => 'journal_book_template_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}