<?php

/**
 * BaseIndustry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $title
 * @property string $description
 * @property GeneralLibraryAdditionInfo $GeneralLibraryAdditionInfo
 * 
 * @method string                     getCode()                       Returns the current record's "code" value
 * @method string                     getTitle()                      Returns the current record's "title" value
 * @method string                     getDescription()                Returns the current record's "description" value
 * @method GeneralLibraryAdditionInfo getGeneralLibraryAdditionInfo() Returns the current record's "GeneralLibraryAdditionInfo" value
 * @method Industry                   setCode()                       Sets the current record's "code" value
 * @method Industry                   setTitle()                      Sets the current record's "title" value
 * @method Industry                   setDescription()                Sets the current record's "description" value
 * @method Industry                   setGeneralLibraryAdditionInfo() Sets the current record's "GeneralLibraryAdditionInfo" value
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIndustry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('industry');
        $this->hasColumn('code', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GeneralLibraryAdditionInfo', array(
             'local' => 'id',
             'foreign' => 'industry_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}