<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RolePrivileges', 'doctrine');

/**
 * BaseRolePrivileges
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $role_id
 * @property string $name
 * @property string $description
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer        getId()          Returns the current record's "id" value
 * @method string         getRoleId()      Returns the current record's "role_id" value
 * @method string         getName()        Returns the current record's "name" value
 * @method string         getDescription() Returns the current record's "description" value
 * @method timestamp      getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp      getUpdatedAt()   Returns the current record's "updated_at" value
 * @method RolePrivileges setId()          Sets the current record's "id" value
 * @method RolePrivileges setRoleId()      Sets the current record's "role_id" value
 * @method RolePrivileges setName()        Sets the current record's "name" value
 * @method RolePrivileges setDescription() Sets the current record's "description" value
 * @method RolePrivileges setCreatedAt()   Sets the current record's "created_at" value
 * @method RolePrivileges setUpdatedAt()   Sets the current record's "updated_at" value
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRolePrivileges extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('role_privileges');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('role_id', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'PHP',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}