<?php

/**
 * BaseTaxRate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property decimal $rate
 * @property date $effectivity_date
 * @property enum $type
 * @property Doctrine_Collection $CheckVoucherAccountEntryOutputVatEntry
 * @property Doctrine_Collection $AccountsPayableVoucherAccountEntryOutputVatEntry
 * @property Doctrine_Collection $DebitCreditMemoAccountEntryOutputVatEntry
 * @property Doctrine_Collection $ReceiptAccountEntryOutputVatEntry
 * @property Doctrine_Collection $InvoiceAccountEntryOutputVatEntry
 * @property Doctrine_Collection $JournalVoucherAccountEntryOutputVatEntry
 * @property Doctrine_Collection $PettyCashVoucherAccountEntryOutputVatEntry
 * 
 * @method decimal             getRate()                                             Returns the current record's "rate" value
 * @method date                getEffectivityDate()                                  Returns the current record's "effectivity_date" value
 * @method enum                getType()                                             Returns the current record's "type" value
 * @method Doctrine_Collection getCheckVoucherAccountEntryOutputVatEntry()           Returns the current record's "CheckVoucherAccountEntryOutputVatEntry" collection
 * @method Doctrine_Collection getAccountsPayableVoucherAccountEntryOutputVatEntry() Returns the current record's "AccountsPayableVoucherAccountEntryOutputVatEntry" collection
 * @method Doctrine_Collection getDebitCreditMemoAccountEntryOutputVatEntry()        Returns the current record's "DebitCreditMemoAccountEntryOutputVatEntry" collection
 * @method Doctrine_Collection getReceiptAccountEntryOutputVatEntry()                Returns the current record's "ReceiptAccountEntryOutputVatEntry" collection
 * @method Doctrine_Collection getInvoiceAccountEntryOutputVatEntry()                Returns the current record's "InvoiceAccountEntryOutputVatEntry" collection
 * @method Doctrine_Collection getJournalVoucherAccountEntryOutputVatEntry()         Returns the current record's "JournalVoucherAccountEntryOutputVatEntry" collection
 * @method Doctrine_Collection getPettyCashVoucherAccountEntryOutputVatEntry()       Returns the current record's "PettyCashVoucherAccountEntryOutputVatEntry" collection
 * @method TaxRate             setRate()                                             Sets the current record's "rate" value
 * @method TaxRate             setEffectivityDate()                                  Sets the current record's "effectivity_date" value
 * @method TaxRate             setType()                                             Sets the current record's "type" value
 * @method TaxRate             setCheckVoucherAccountEntryOutputVatEntry()           Sets the current record's "CheckVoucherAccountEntryOutputVatEntry" collection
 * @method TaxRate             setAccountsPayableVoucherAccountEntryOutputVatEntry() Sets the current record's "AccountsPayableVoucherAccountEntryOutputVatEntry" collection
 * @method TaxRate             setDebitCreditMemoAccountEntryOutputVatEntry()        Sets the current record's "DebitCreditMemoAccountEntryOutputVatEntry" collection
 * @method TaxRate             setReceiptAccountEntryOutputVatEntry()                Sets the current record's "ReceiptAccountEntryOutputVatEntry" collection
 * @method TaxRate             setInvoiceAccountEntryOutputVatEntry()                Sets the current record's "InvoiceAccountEntryOutputVatEntry" collection
 * @method TaxRate             setJournalVoucherAccountEntryOutputVatEntry()         Sets the current record's "JournalVoucherAccountEntryOutputVatEntry" collection
 * @method TaxRate             setPettyCashVoucherAccountEntryOutputVatEntry()       Sets the current record's "PettyCashVoucherAccountEntryOutputVatEntry" collection
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaxRate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tax_rate');
        $this->hasColumn('rate', 'decimal', 4, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 4,
             ));
        $this->hasColumn('effectivity_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'INPUT',
              1 => 'OUTPUT',
             ),
             'default' => 'INPUT',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CheckVoucherAccountEntryOutputVatEntry', array(
             'local' => 'id',
             'foreign' => 'tax_rate_id'));

        $this->hasMany('AccountsPayableVoucherAccountEntryOutputVatEntry', array(
             'local' => 'id',
             'foreign' => 'tax_rate_id'));

        $this->hasMany('DebitCreditMemoAccountEntryOutputVatEntry', array(
             'local' => 'id',
             'foreign' => 'tax_rate_id'));

        $this->hasMany('ReceiptAccountEntryOutputVatEntry', array(
             'local' => 'id',
             'foreign' => 'tax_rate_id'));

        $this->hasMany('InvoiceAccountEntryOutputVatEntry', array(
             'local' => 'id',
             'foreign' => 'tax_rate_id'));

        $this->hasMany('JournalVoucherAccountEntryOutputVatEntry', array(
             'local' => 'id',
             'foreign' => 'tax_rate_id'));

        $this->hasMany('PettyCashVoucherAccountEntryOutputVatEntry', array(
             'local' => 'id',
             'foreign' => 'tax_rate_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}