<?php

/**
 * BaseGeneralLibraryCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $GeneralLibrary
 * 
 * @method string                 getName()           Returns the current record's "name" value
 * @method string                 getDescription()    Returns the current record's "description" value
 * @method Doctrine_Collection    getGeneralLibrary() Returns the current record's "GeneralLibrary" collection
 * @method GeneralLibraryCategory setName()           Sets the current record's "name" value
 * @method GeneralLibraryCategory setDescription()    Sets the current record's "description" value
 * @method GeneralLibraryCategory setGeneralLibrary() Sets the current record's "GeneralLibrary" collection
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGeneralLibraryCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('general_library_category');
        $this->hasColumn('name', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 60,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GeneralLibrary', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}