<?php

/**
 * BasePettyCashVoucherAccountEntryOutputVat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $chart_of_account_id
 * @property int $general_library_id
 * @property string $tin_number
 * @property ChartOfAccount $ChartOfAccount
 * @property GeneralLibrary $GeneralLibrary
 * @property Doctrine_Collection $PettyCashVoucherAccountEntryOutputVatEntry
 * 
 * @method int                                   getChartOfAccountId()                           Returns the current record's "chart_of_account_id" value
 * @method int                                   getGeneralLibraryId()                           Returns the current record's "general_library_id" value
 * @method string                                getTinNumber()                                  Returns the current record's "tin_number" value
 * @method ChartOfAccount                        getChartOfAccount()                             Returns the current record's "ChartOfAccount" value
 * @method GeneralLibrary                        getGeneralLibrary()                             Returns the current record's "GeneralLibrary" value
 * @method Doctrine_Collection                   getPettyCashVoucherAccountEntryOutputVatEntry() Returns the current record's "PettyCashVoucherAccountEntryOutputVatEntry" collection
 * @method PettyCashVoucherAccountEntryOutputVat setChartOfAccountId()                           Sets the current record's "chart_of_account_id" value
 * @method PettyCashVoucherAccountEntryOutputVat setGeneralLibraryId()                           Sets the current record's "general_library_id" value
 * @method PettyCashVoucherAccountEntryOutputVat setTinNumber()                                  Sets the current record's "tin_number" value
 * @method PettyCashVoucherAccountEntryOutputVat setChartOfAccount()                             Sets the current record's "ChartOfAccount" value
 * @method PettyCashVoucherAccountEntryOutputVat setGeneralLibrary()                             Sets the current record's "GeneralLibrary" value
 * @method PettyCashVoucherAccountEntryOutputVat setPettyCashVoucherAccountEntryOutputVatEntry() Sets the current record's "PettyCashVoucherAccountEntryOutputVatEntry" collection
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePettyCashVoucherAccountEntryOutputVat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('petty_cash_voucher_account_entry_output_vat');
        $this->hasColumn('chart_of_account_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('general_library_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('tin_number', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ChartOfAccount', array(
             'local' => 'chart_of_account_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('GeneralLibrary', array(
             'local' => 'general_library_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('PettyCashVoucherAccountEntryOutputVatEntry', array(
             'local' => 'id',
             'foreign' => 'petty_cash_voucher_account_entry_output_vat_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}