<?php

/**
 * BaseCheckVoucherAccountEntryOutputVat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $check_voucher_number
 * @property int $chart_of_account_id
 * @property int $general_library_id
 * @property string $tin_number
 * @property ChartOfAccount $ChartOfAccount
 * @property GeneralLibrary $GeneralLibrary
 * @property Doctrine_Collection $CheckVoucherAccountEntryOutputVatEntry
 * 
 * @method int                               getCheckVoucherNumber()                     Returns the current record's "check_voucher_number" value
 * @method int                               getChartOfAccountId()                       Returns the current record's "chart_of_account_id" value
 * @method int                               getGeneralLibraryId()                       Returns the current record's "general_library_id" value
 * @method string                            getTinNumber()                              Returns the current record's "tin_number" value
 * @method ChartOfAccount                    getChartOfAccount()                         Returns the current record's "ChartOfAccount" value
 * @method GeneralLibrary                    getGeneralLibrary()                         Returns the current record's "GeneralLibrary" value
 * @method Doctrine_Collection               getCheckVoucherAccountEntryOutputVatEntry() Returns the current record's "CheckVoucherAccountEntryOutputVatEntry" collection
 * @method CheckVoucherAccountEntryOutputVat setCheckVoucherNumber()                     Sets the current record's "check_voucher_number" value
 * @method CheckVoucherAccountEntryOutputVat setChartOfAccountId()                       Sets the current record's "chart_of_account_id" value
 * @method CheckVoucherAccountEntryOutputVat setGeneralLibraryId()                       Sets the current record's "general_library_id" value
 * @method CheckVoucherAccountEntryOutputVat setTinNumber()                              Sets the current record's "tin_number" value
 * @method CheckVoucherAccountEntryOutputVat setChartOfAccount()                         Sets the current record's "ChartOfAccount" value
 * @method CheckVoucherAccountEntryOutputVat setGeneralLibrary()                         Sets the current record's "GeneralLibrary" value
 * @method CheckVoucherAccountEntryOutputVat setCheckVoucherAccountEntryOutputVatEntry() Sets the current record's "CheckVoucherAccountEntryOutputVatEntry" collection
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCheckVoucherAccountEntryOutputVat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('check_voucher_account_entry_output_vat');
        $this->hasColumn('check_voucher_number', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('chart_of_account_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('general_library_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('tin_number', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ChartOfAccount', array(
             'local' => 'chart_of_account_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('GeneralLibrary', array(
             'local' => 'general_library_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('CheckVoucherAccountEntryOutputVatEntry', array(
             'local' => 'id',
             'foreign' => 'check_voucher_account_entry_output_vat_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}