<?php

/**
 * BaseAccountsPayableVoucherAccountEntryOutputVat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $accounts_payable_voucher_number
 * @property int $chart_of_account_id
 * @property int $general_library_id
 * @property string $tin_number
 * @property ChartOfAccount $ChartOfAccount
 * @property GeneralLibrary $GeneralLibrary
 * @property Doctrine_Collection $AccountsPayableVoucherAccountEntryOutputVatEntry
 * 
 * @method int                                         getAccountsPayableVoucherNumber()                     Returns the current record's "accounts_payable_voucher_number" value
 * @method int                                         getChartOfAccountId()                                 Returns the current record's "chart_of_account_id" value
 * @method int                                         getGeneralLibraryId()                                 Returns the current record's "general_library_id" value
 * @method string                                      getTinNumber()                                        Returns the current record's "tin_number" value
 * @method ChartOfAccount                              getChartOfAccount()                                   Returns the current record's "ChartOfAccount" value
 * @method GeneralLibrary                              getGeneralLibrary()                                   Returns the current record's "GeneralLibrary" value
 * @method Doctrine_Collection                         getAccountsPayableVoucherAccountEntryOutputVatEntry() Returns the current record's "AccountsPayableVoucherAccountEntryOutputVatEntry" collection
 * @method AccountsPayableVoucherAccountEntryOutputVat setAccountsPayableVoucherNumber()                     Sets the current record's "accounts_payable_voucher_number" value
 * @method AccountsPayableVoucherAccountEntryOutputVat setChartOfAccountId()                                 Sets the current record's "chart_of_account_id" value
 * @method AccountsPayableVoucherAccountEntryOutputVat setGeneralLibraryId()                                 Sets the current record's "general_library_id" value
 * @method AccountsPayableVoucherAccountEntryOutputVat setTinNumber()                                        Sets the current record's "tin_number" value
 * @method AccountsPayableVoucherAccountEntryOutputVat setChartOfAccount()                                   Sets the current record's "ChartOfAccount" value
 * @method AccountsPayableVoucherAccountEntryOutputVat setGeneralLibrary()                                   Sets the current record's "GeneralLibrary" value
 * @method AccountsPayableVoucherAccountEntryOutputVat setAccountsPayableVoucherAccountEntryOutputVatEntry() Sets the current record's "AccountsPayableVoucherAccountEntryOutputVatEntry" collection
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccountsPayableVoucherAccountEntryOutputVat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('accounts_payable_voucher_account_entry_output_vat');
        $this->hasColumn('accounts_payable_voucher_number', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('chart_of_account_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('general_library_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('tin_number', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ChartOfAccount', array(
             'local' => 'chart_of_account_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('GeneralLibrary', array(
             'local' => 'general_library_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('AccountsPayableVoucherAccountEntryOutputVatEntry', array(
             'local' => 'id',
             'foreign' => 'accounts_payable_voucher_account_entry_output_vat_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}