<?php

/**
 * BaseParticularTemplateEntry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $particular_template_id
 * @property string $title
 * @property decimal $amount
 * @property enum $vat_application
 * @property int $tax_expanded_withheld_id
 * @property int $tax_final_withheld_id
 * @property decimal $total
 * @property ParticularTemplate $ParticularTemplate
 * @property TaxExpandedWithheld $TaxExpandedWithheld
 * @property TaxFinalWithheld $TaxFinalWithheld
 * 
 * @method int                     getParticularTemplateId()     Returns the current record's "particular_template_id" value
 * @method string                  getTitle()                    Returns the current record's "title" value
 * @method decimal                 getAmount()                   Returns the current record's "amount" value
 * @method enum                    getVatApplication()           Returns the current record's "vat_application" value
 * @method int                     getTaxExpandedWithheldId()    Returns the current record's "tax_expanded_withheld_id" value
 * @method int                     getTaxFinalWithheldId()       Returns the current record's "tax_final_withheld_id" value
 * @method decimal                 getTotal()                    Returns the current record's "total" value
 * @method ParticularTemplate      getParticularTemplate()       Returns the current record's "ParticularTemplate" value
 * @method TaxExpandedWithheld     getTaxExpandedWithheld()      Returns the current record's "TaxExpandedWithheld" value
 * @method TaxFinalWithheld        getTaxFinalWithheld()         Returns the current record's "TaxFinalWithheld" value
 * @method ParticularTemplateEntry setParticularTemplateId()     Sets the current record's "particular_template_id" value
 * @method ParticularTemplateEntry setTitle()                    Sets the current record's "title" value
 * @method ParticularTemplateEntry setAmount()                   Sets the current record's "amount" value
 * @method ParticularTemplateEntry setVatApplication()           Sets the current record's "vat_application" value
 * @method ParticularTemplateEntry setTaxExpandedWithheldId()    Sets the current record's "tax_expanded_withheld_id" value
 * @method ParticularTemplateEntry setTaxFinalWithheldId()       Sets the current record's "tax_final_withheld_id" value
 * @method ParticularTemplateEntry setTotal()                    Sets the current record's "total" value
 * @method ParticularTemplateEntry setParticularTemplate()       Sets the current record's "ParticularTemplate" value
 * @method ParticularTemplateEntry setTaxExpandedWithheld()      Sets the current record's "TaxExpandedWithheld" value
 * @method ParticularTemplateEntry setTaxFinalWithheld()         Sets the current record's "TaxFinalWithheld" value
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParticularTemplateEntry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('particular_template_entry');
        $this->hasColumn('particular_template_id', 'int', 11, array(
             'type' => 'int',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('title', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('amount', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'default' => 0,
             'notnull' => true,
             'length' => 12,
             ));
        $this->hasColumn('vat_application', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'VAT_EXEMPT',
              1 => 'VAT_ZERO_PERCENT',
              2 => 'VAT_INCLUSIVE',
              3 => 'VAT_EXCLUSIVE',
             ),
             'default' => 'VAT_INCLUSIVE',
             ));
        $this->hasColumn('tax_expanded_withheld_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('tax_final_withheld_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('total', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'default' => 0,
             'notnull' => true,
             'length' => 12,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ParticularTemplate', array(
             'local' => 'particular_template_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('TaxExpandedWithheld', array(
             'local' => 'tax_expanded_withheld_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('TaxFinalWithheld', array(
             'local' => 'tax_final_withheld_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}