<?php

/**
 * BaseCashVoucherEntry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $check_voucher_id
 * @property int $general_library_id
 * @property int $chart_of_account_id
 * @property decimal $amount
 * @property date $date
 * @property ChartOfAccount $ChartOfAccount
 * @property CheckVoucher $CheckVoucher
 * @property GeneralLibrary $GeneralLibrary
 * 
 * @method int              getCheckVoucherId()      Returns the current record's "check_voucher_id" value
 * @method int              getGeneralLibraryId()    Returns the current record's "general_library_id" value
 * @method int              getChartOfAccountId()    Returns the current record's "chart_of_account_id" value
 * @method decimal          getAmount()              Returns the current record's "amount" value
 * @method date             getDate()                Returns the current record's "date" value
 * @method ChartOfAccount   getChartOfAccount()      Returns the current record's "ChartOfAccount" value
 * @method CheckVoucher     getCheckVoucher()        Returns the current record's "CheckVoucher" value
 * @method GeneralLibrary   getGeneralLibrary()      Returns the current record's "GeneralLibrary" value
 * @method CashVoucherEntry setCheckVoucherId()      Sets the current record's "check_voucher_id" value
 * @method CashVoucherEntry setGeneralLibraryId()    Sets the current record's "general_library_id" value
 * @method CashVoucherEntry setChartOfAccountId()    Sets the current record's "chart_of_account_id" value
 * @method CashVoucherEntry setAmount()              Sets the current record's "amount" value
 * @method CashVoucherEntry setDate()                Sets the current record's "date" value
 * @method CashVoucherEntry setChartOfAccount()      Sets the current record's "ChartOfAccount" value
 * @method CashVoucherEntry setCheckVoucher()        Sets the current record's "CheckVoucher" value
 * @method CashVoucherEntry setGeneralLibrary()      Sets the current record's "GeneralLibrary" value
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCashVoucherEntry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cash_voucher_entry');
        $this->hasColumn('check_voucher_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('general_library_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('chart_of_account_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('amount', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'default' => 0,
             'notnull' => true,
             'length' => 12,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ChartOfAccount', array(
             'local' => 'chart_of_account_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('CheckVoucher', array(
             'local' => 'check_voucher_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('GeneralLibrary', array(
             'local' => 'general_library_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}