<?php

/**
 * BaseBank
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $name
 * @property string $description
 * @property string $logo
 * @property boolean $status
 * @property Doctrine_Collection $BankAccount
 * @property Doctrine_Collection $ReceiptCheckEntry
 * 
 * @method string              getCode()              Returns the current record's "code" value
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getDescription()       Returns the current record's "description" value
 * @method string              getLogo()              Returns the current record's "logo" value
 * @method boolean             getStatus()            Returns the current record's "status" value
 * @method Doctrine_Collection getBankAccount()       Returns the current record's "BankAccount" collection
 * @method Doctrine_Collection getReceiptCheckEntry() Returns the current record's "ReceiptCheckEntry" collection
 * @method Bank                setCode()              Sets the current record's "code" value
 * @method Bank                setName()              Sets the current record's "name" value
 * @method Bank                setDescription()       Sets the current record's "description" value
 * @method Bank                setLogo()              Sets the current record's "logo" value
 * @method Bank                setStatus()            Sets the current record's "status" value
 * @method Bank                setBankAccount()       Sets the current record's "BankAccount" collection
 * @method Bank                setReceiptCheckEntry() Sets the current record's "ReceiptCheckEntry" collection
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBank extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bank');
        $this->hasColumn('code', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 10,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('logo', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BankAccount', array(
             'local' => 'id',
             'foreign' => 'bank_id'));

        $this->hasMany('ReceiptCheckEntry', array(
             'local' => 'id',
             'foreign' => 'bank_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}