<?php

/**
 * BaseReceiptCashEntry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $receipt_id
 * @property int $general_library_id
 * @property int $chart_of_account_id
 * @property date $date
 * @property decimal $amount
 * @property Receipt $Receipt
 * @property ChartOfAccount $ChartOfAccount
 * @property GeneralLibrary $GeneralLibrary
 * 
 * @method int              getReceiptId()           Returns the current record's "receipt_id" value
 * @method int              getGeneralLibraryId()    Returns the current record's "general_library_id" value
 * @method int              getChartOfAccountId()    Returns the current record's "chart_of_account_id" value
 * @method date             getDate()                Returns the current record's "date" value
 * @method decimal          getAmount()              Returns the current record's "amount" value
 * @method Receipt          getReceipt()             Returns the current record's "Receipt" value
 * @method ChartOfAccount   getChartOfAccount()      Returns the current record's "ChartOfAccount" value
 * @method GeneralLibrary   getGeneralLibrary()      Returns the current record's "GeneralLibrary" value
 * @method ReceiptCashEntry setReceiptId()           Sets the current record's "receipt_id" value
 * @method ReceiptCashEntry setGeneralLibraryId()    Sets the current record's "general_library_id" value
 * @method ReceiptCashEntry setChartOfAccountId()    Sets the current record's "chart_of_account_id" value
 * @method ReceiptCashEntry setDate()                Sets the current record's "date" value
 * @method ReceiptCashEntry setAmount()              Sets the current record's "amount" value
 * @method ReceiptCashEntry setReceipt()             Sets the current record's "Receipt" value
 * @method ReceiptCashEntry setChartOfAccount()      Sets the current record's "ChartOfAccount" value
 * @method ReceiptCashEntry setGeneralLibrary()      Sets the current record's "GeneralLibrary" value
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReceiptCashEntry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('receipt_cash_entry');
        $this->hasColumn('receipt_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('general_library_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('chart_of_account_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('amount', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'default' => 0,
             'notnull' => true,
             'length' => 12,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Receipt', array(
             'local' => 'receipt_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ChartOfAccount', array(
             'local' => 'chart_of_account_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('GeneralLibrary', array(
             'local' => 'general_library_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}