<?php

/**
 * BaseInvoiceAccountEntry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $invoice_id
 * @property int $chart_of_account_id
 * @property int $project_id
 * @property int $department_id
 * @property string $dn_reference
 * @property int $general_library_id
 * @property decimal $debit
 * @property decimal $credit
 * @property Invoice $Invoice
 * @property ChartOfAccount $ChartOfAccount
 * @property Project $Project
 * @property Department $Department
 * @property GeneralLibrary $GeneralLibrary
 * 
 * @method int                 getInvoiceId()           Returns the current record's "invoice_id" value
 * @method int                 getChartOfAccountId()    Returns the current record's "chart_of_account_id" value
 * @method int                 getProjectId()           Returns the current record's "project_id" value
 * @method int                 getDepartmentId()        Returns the current record's "department_id" value
 * @method string              getDnReference()         Returns the current record's "dn_reference" value
 * @method int                 getGeneralLibraryId()    Returns the current record's "general_library_id" value
 * @method decimal             getDebit()               Returns the current record's "debit" value
 * @method decimal             getCredit()              Returns the current record's "credit" value
 * @method Invoice             getInvoice()             Returns the current record's "Invoice" value
 * @method ChartOfAccount      getChartOfAccount()      Returns the current record's "ChartOfAccount" value
 * @method Project             getProject()             Returns the current record's "Project" value
 * @method Department          getDepartment()          Returns the current record's "Department" value
 * @method GeneralLibrary      getGeneralLibrary()      Returns the current record's "GeneralLibrary" value
 * @method InvoiceAccountEntry setInvoiceId()           Sets the current record's "invoice_id" value
 * @method InvoiceAccountEntry setChartOfAccountId()    Sets the current record's "chart_of_account_id" value
 * @method InvoiceAccountEntry setProjectId()           Sets the current record's "project_id" value
 * @method InvoiceAccountEntry setDepartmentId()        Sets the current record's "department_id" value
 * @method InvoiceAccountEntry setDnReference()         Sets the current record's "dn_reference" value
 * @method InvoiceAccountEntry setGeneralLibraryId()    Sets the current record's "general_library_id" value
 * @method InvoiceAccountEntry setDebit()               Sets the current record's "debit" value
 * @method InvoiceAccountEntry setCredit()              Sets the current record's "credit" value
 * @method InvoiceAccountEntry setInvoice()             Sets the current record's "Invoice" value
 * @method InvoiceAccountEntry setChartOfAccount()      Sets the current record's "ChartOfAccount" value
 * @method InvoiceAccountEntry setProject()             Sets the current record's "Project" value
 * @method InvoiceAccountEntry setDepartment()          Sets the current record's "Department" value
 * @method InvoiceAccountEntry setGeneralLibrary()      Sets the current record's "GeneralLibrary" value
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInvoiceAccountEntry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('invoice_account_entry');
        $this->hasColumn('invoice_id', 'int', 11, array(
             'type' => 'int',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('chart_of_account_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('project_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('department_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('dn_reference', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('general_library_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('debit', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'default' => 0,
             'notnull' => true,
             'length' => 12,
             ));
        $this->hasColumn('credit', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'default' => 0,
             'notnull' => true,
             'length' => 12,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Invoice', array(
             'local' => 'invoice_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ChartOfAccount', array(
             'local' => 'chart_of_account_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Department', array(
             'local' => 'department_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('GeneralLibrary', array(
             'local' => 'general_library_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}