<?php

/**
 * BaseChartOfAccountGroupCode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $chart_of_account_id
 * @property int $group_code_id
 * @property ChartOfAccount $ChartOfAccount
 * @property GroupCode $GroupCode
 * 
 * @method int                     getChartOfAccountId()    Returns the current record's "chart_of_account_id" value
 * @method int                     getGroupCodeId()         Returns the current record's "group_code_id" value
 * @method ChartOfAccount          getChartOfAccount()      Returns the current record's "ChartOfAccount" value
 * @method GroupCode               getGroupCode()           Returns the current record's "GroupCode" value
 * @method ChartOfAccountGroupCode setChartOfAccountId()    Sets the current record's "chart_of_account_id" value
 * @method ChartOfAccountGroupCode setGroupCodeId()         Sets the current record's "group_code_id" value
 * @method ChartOfAccountGroupCode setChartOfAccount()      Sets the current record's "ChartOfAccount" value
 * @method ChartOfAccountGroupCode setGroupCode()           Sets the current record's "GroupCode" value
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChartOfAccountGroupCode extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chart_of_account_group_code');
        $this->hasColumn('chart_of_account_id', 'int', 11, array(
             'type' => 'int',
             'primary' => true,
             'length' => 11,
             ));
        $this->hasColumn('group_code_id', 'int', 11, array(
             'type' => 'int',
             'primary' => true,
             'length' => 11,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ChartOfAccount', array(
             'local' => 'chart_of_account_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('GroupCode', array(
             'local' => 'group_code_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}