<?php

/**
 * BaseAccountsPayableVoucher
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $book_id
 * @property string $voucher_number
 * @property int $general_library_id
 * @property int $currency_id
 * @property string $si_dr_number
 * @property string $purchase_order_number
 * @property date $date_received
 * @property date $period
 * @property date $due_date
 * @property int $terms_of_payment_id
 * @property string $header_message
 * @property string $footer_message
 * @property decimal $total_amount
 * @property enum $status
 * @property Book $Book
 * @property GeneralLibrary $GeneralLibrary
 * @property Currency $Currency
 * @property TermsOfPayment $TermsOfPayment
 * @property Doctrine_Collection $AccountsPayableVoucherParticularEntry
 * @property Doctrine_Collection $AccountsPayableVoucherAccountEntry
 * 
 * @method int                    getBookId()                                Returns the current record's "book_id" value
 * @method string                 getVoucherNumber()                         Returns the current record's "voucher_number" value
 * @method int                    getGeneralLibraryId()                      Returns the current record's "general_library_id" value
 * @method int                    getCurrencyId()                            Returns the current record's "currency_id" value
 * @method string                 getSiDrNumber()                            Returns the current record's "si_dr_number" value
 * @method string                 getPurchaseOrderNumber()                   Returns the current record's "purchase_order_number" value
 * @method date                   getDateReceived()                          Returns the current record's "date_received" value
 * @method date                   getPeriod()                                Returns the current record's "period" value
 * @method date                   getDueDate()                               Returns the current record's "due_date" value
 * @method int                    getTermsOfPaymentId()                      Returns the current record's "terms_of_payment_id" value
 * @method string                 getHeaderMessage()                         Returns the current record's "header_message" value
 * @method string                 getFooterMessage()                         Returns the current record's "footer_message" value
 * @method decimal                getTotalAmount()                           Returns the current record's "total_amount" value
 * @method enum                   getStatus()                                Returns the current record's "status" value
 * @method Book                   getBook()                                  Returns the current record's "Book" value
 * @method GeneralLibrary         getGeneralLibrary()                        Returns the current record's "GeneralLibrary" value
 * @method Currency               getCurrency()                              Returns the current record's "Currency" value
 * @method TermsOfPayment         getTermsOfPayment()                        Returns the current record's "TermsOfPayment" value
 * @method Doctrine_Collection    getAccountsPayableVoucherParticularEntry() Returns the current record's "AccountsPayableVoucherParticularEntry" collection
 * @method Doctrine_Collection    getAccountsPayableVoucherAccountEntry()    Returns the current record's "AccountsPayableVoucherAccountEntry" collection
 * @method AccountsPayableVoucher setBookId()                                Sets the current record's "book_id" value
 * @method AccountsPayableVoucher setVoucherNumber()                         Sets the current record's "voucher_number" value
 * @method AccountsPayableVoucher setGeneralLibraryId()                      Sets the current record's "general_library_id" value
 * @method AccountsPayableVoucher setCurrencyId()                            Sets the current record's "currency_id" value
 * @method AccountsPayableVoucher setSiDrNumber()                            Sets the current record's "si_dr_number" value
 * @method AccountsPayableVoucher setPurchaseOrderNumber()                   Sets the current record's "purchase_order_number" value
 * @method AccountsPayableVoucher setDateReceived()                          Sets the current record's "date_received" value
 * @method AccountsPayableVoucher setPeriod()                                Sets the current record's "period" value
 * @method AccountsPayableVoucher setDueDate()                               Sets the current record's "due_date" value
 * @method AccountsPayableVoucher setTermsOfPaymentId()                      Sets the current record's "terms_of_payment_id" value
 * @method AccountsPayableVoucher setHeaderMessage()                         Sets the current record's "header_message" value
 * @method AccountsPayableVoucher setFooterMessage()                         Sets the current record's "footer_message" value
 * @method AccountsPayableVoucher setTotalAmount()                           Sets the current record's "total_amount" value
 * @method AccountsPayableVoucher setStatus()                                Sets the current record's "status" value
 * @method AccountsPayableVoucher setBook()                                  Sets the current record's "Book" value
 * @method AccountsPayableVoucher setGeneralLibrary()                        Sets the current record's "GeneralLibrary" value
 * @method AccountsPayableVoucher setCurrency()                              Sets the current record's "Currency" value
 * @method AccountsPayableVoucher setTermsOfPayment()                        Sets the current record's "TermsOfPayment" value
 * @method AccountsPayableVoucher setAccountsPayableVoucherParticularEntry() Sets the current record's "AccountsPayableVoucherParticularEntry" collection
 * @method AccountsPayableVoucher setAccountsPayableVoucherAccountEntry()    Sets the current record's "AccountsPayableVoucherAccountEntry" collection
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccountsPayableVoucher extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('accounts_payable_voucher');
        $this->hasColumn('book_id', 'int', 11, array(
             'type' => 'int',
             'notnull' => true,
             'default' => '0',
             'length' => 11,
             ));
        $this->hasColumn('voucher_number', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('general_library_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('currency_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('si_dr_number', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('purchase_order_number', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('date_received', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('period', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('due_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('terms_of_payment_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('header_message', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('footer_message', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('total_amount', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'default' => 0,
             'notnull' => true,
             'length' => 12,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'FULL',
              1 => 'PARTIAL',
             ),
             'default' => 'FULL',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Book', array(
             'local' => 'book_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('GeneralLibrary', array(
             'local' => 'general_library_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Currency', array(
             'local' => 'currency_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('TermsOfPayment', array(
             'local' => 'terms_of_payment_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('AccountsPayableVoucherParticularEntry', array(
             'local' => 'id',
             'foreign' => 'accounts_payable_voucher_id'));

        $this->hasMany('AccountsPayableVoucherAccountEntry', array(
             'local' => 'id',
             'foreign' => 'accounts_payable_voucher_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}