<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserRoles', 'doctrine');

/**
 * BaseUserRoles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property string $status
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $Users
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getCode()       Returns the current record's "code" value
 * @method string              getName()       Returns the current record's "name" value
 * @method string              getStatus()     Returns the current record's "status" value
 * @method timestamp           getCreatedAt()  Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()  Returns the current record's "updated_at" value
 * @method Doctrine_Collection getUsers()      Returns the current record's "Users" collection
 * @method UserRoles           setId()         Sets the current record's "id" value
 * @method UserRoles           setCode()       Sets the current record's "code" value
 * @method UserRoles           setName()       Sets the current record's "name" value
 * @method UserRoles           setStatus()     Sets the current record's "status" value
 * @method UserRoles           setCreatedAt()  Sets the current record's "created_at" value
 * @method UserRoles           setUpdatedAt()  Sets the current record's "updated_at" value
 * @method UserRoles           setUsers()      Sets the current record's "Users" collection
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserRoles extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_roles');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('code', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'PHP',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('status', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Users', array(
             'local' => 'id',
             'foreign' => 'role_id'));
    }
}