<?php

/**
 * BaseJournalBookParticularTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $journal_book_id
 * @property integer $particular_template_id
 * @property JournalBook $JournalBook
 * @property ParticularTemplate $ParticularTemplate
 * 
 * @method integer                       getJournalBookId()          Returns the current record's "journal_book_id" value
 * @method integer                       getParticularTemplateId()   Returns the current record's "particular_template_id" value
 * @method JournalBook                   getJournalBook()            Returns the current record's "JournalBook" value
 * @method ParticularTemplate            getParticularTemplate()     Returns the current record's "ParticularTemplate" value
 * @method JournalBookParticularTemplate setJournalBookId()          Sets the current record's "journal_book_id" value
 * @method JournalBookParticularTemplate setParticularTemplateId()   Sets the current record's "particular_template_id" value
 * @method JournalBookParticularTemplate setJournalBook()            Sets the current record's "JournalBook" value
 * @method JournalBookParticularTemplate setParticularTemplate()     Sets the current record's "ParticularTemplate" value
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJournalBookParticularTemplate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('journal_book_particular_template');
        $this->hasColumn('journal_book_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '',
             'length' => 11,
             ));
        $this->hasColumn('particular_template_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '',
             'length' => 11,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('JournalBook', array(
             'local' => 'journal_book_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ParticularTemplate', array(
             'local' => 'particular_template_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}