<?php

/**
 * BaseCheckVoucher
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $book_id
 * @property string $voucher_number
 * @property int $general_library_id
 * @property int $currency_id
 * @property date $date_received
 * @property date $period
 * @property date $due_date
 * @property string $header_message
 * @property string $footer_message
 * @property string $si_dr_number
 * @property decimal $total_amount
 * @property enum $status
 * @property Book $Book
 * @property GeneralLibrary $GeneralLibrary
 * @property Currency $Currency
 * @property Doctrine_Collection $CheckVoucherParticularEntry
 * @property Doctrine_Collection $CheckVoucherAccountEntry
 * @property Doctrine_Collection $CashVoucherEntry
 * @property Doctrine_Collection $CheckVoucherEntry
 * 
 * @method int                 getBookId()                      Returns the current record's "book_id" value
 * @method string              getVoucherNumber()               Returns the current record's "voucher_number" value
 * @method int                 getGeneralLibraryId()            Returns the current record's "general_library_id" value
 * @method int                 getCurrencyId()                  Returns the current record's "currency_id" value
 * @method date                getDateReceived()                Returns the current record's "date_received" value
 * @method date                getPeriod()                      Returns the current record's "period" value
 * @method date                getDueDate()                     Returns the current record's "due_date" value
 * @method string              getHeaderMessage()               Returns the current record's "header_message" value
 * @method string              getFooterMessage()               Returns the current record's "footer_message" value
 * @method string              getSiDrNumber()                  Returns the current record's "si_dr_number" value
 * @method decimal             getTotalAmount()                 Returns the current record's "total_amount" value
 * @method enum                getStatus()                      Returns the current record's "status" value
 * @method Book                getBook()                        Returns the current record's "Book" value
 * @method GeneralLibrary      getGeneralLibrary()              Returns the current record's "GeneralLibrary" value
 * @method Currency            getCurrency()                    Returns the current record's "Currency" value
 * @method Doctrine_Collection getCheckVoucherParticularEntry() Returns the current record's "CheckVoucherParticularEntry" collection
 * @method Doctrine_Collection getCheckVoucherAccountEntry()    Returns the current record's "CheckVoucherAccountEntry" collection
 * @method Doctrine_Collection getCashVoucherEntry()            Returns the current record's "CashVoucherEntry" collection
 * @method Doctrine_Collection getCheckVoucherEntry()           Returns the current record's "CheckVoucherEntry" collection
 * @method CheckVoucher        setBookId()                      Sets the current record's "book_id" value
 * @method CheckVoucher        setVoucherNumber()               Sets the current record's "voucher_number" value
 * @method CheckVoucher        setGeneralLibraryId()            Sets the current record's "general_library_id" value
 * @method CheckVoucher        setCurrencyId()                  Sets the current record's "currency_id" value
 * @method CheckVoucher        setDateReceived()                Sets the current record's "date_received" value
 * @method CheckVoucher        setPeriod()                      Sets the current record's "period" value
 * @method CheckVoucher        setDueDate()                     Sets the current record's "due_date" value
 * @method CheckVoucher        setHeaderMessage()               Sets the current record's "header_message" value
 * @method CheckVoucher        setFooterMessage()               Sets the current record's "footer_message" value
 * @method CheckVoucher        setSiDrNumber()                  Sets the current record's "si_dr_number" value
 * @method CheckVoucher        setTotalAmount()                 Sets the current record's "total_amount" value
 * @method CheckVoucher        setStatus()                      Sets the current record's "status" value
 * @method CheckVoucher        setBook()                        Sets the current record's "Book" value
 * @method CheckVoucher        setGeneralLibrary()              Sets the current record's "GeneralLibrary" value
 * @method CheckVoucher        setCurrency()                    Sets the current record's "Currency" value
 * @method CheckVoucher        setCheckVoucherParticularEntry() Sets the current record's "CheckVoucherParticularEntry" collection
 * @method CheckVoucher        setCheckVoucherAccountEntry()    Sets the current record's "CheckVoucherAccountEntry" collection
 * @method CheckVoucher        setCashVoucherEntry()            Sets the current record's "CashVoucherEntry" collection
 * @method CheckVoucher        setCheckVoucherEntry()           Sets the current record's "CheckVoucherEntry" collection
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCheckVoucher extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('check_voucher');
        $this->hasColumn('book_id', 'int', 11, array(
             'type' => 'int',
             'notnull' => true,
             'default' => '0',
             'length' => 11,
             ));
        $this->hasColumn('voucher_number', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('general_library_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('currency_id', 'int', 11, array(
             'type' => 'int',
             'length' => 11,
             ));
        $this->hasColumn('date_received', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('period', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('due_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('header_message', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('footer_message', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('si_dr_number', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('total_amount', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => 2,
             'default' => 0,
             'notnull' => true,
             'length' => 12,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'FULL',
              1 => 'PARTIAL',
             ),
             'default' => 'FULL',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Book', array(
             'local' => 'book_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('GeneralLibrary', array(
             'local' => 'general_library_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Currency', array(
             'local' => 'currency_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('CheckVoucherParticularEntry', array(
             'local' => 'id',
             'foreign' => 'check_voucher_id'));

        $this->hasMany('CheckVoucherAccountEntry', array(
             'local' => 'id',
             'foreign' => 'check_voucher_id'));

        $this->hasMany('CashVoucherEntry', array(
             'local' => 'id',
             'foreign' => 'check_voucher_id'));

        $this->hasMany('CheckVoucherEntry', array(
             'local' => 'id',
             'foreign' => 'check_voucher_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}