<?php

/**
 * BaseBookCode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $title
 * @property string $description
 * @property Doctrine_Collection $JournalBookCode
 * 
 * @method string              getCode()            Returns the current record's "code" value
 * @method string              getTitle()           Returns the current record's "title" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method Doctrine_Collection getJournalBookCode() Returns the current record's "JournalBookCode" collection
 * @method BookCode            setCode()            Sets the current record's "code" value
 * @method BookCode            setTitle()           Sets the current record's "title" value
 * @method BookCode            setDescription()     Sets the current record's "description" value
 * @method BookCode            setJournalBookCode() Sets the current record's "JournalBookCode" collection
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBookCode extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('book_code');
        $this->hasColumn('code', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('JournalBookCode', array(
             'local' => 'id',
             'foreign' => 'book_code_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}