<?php

/**
 * BaseGroupCode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $title
 * @property string $description
 * @property Doctrine_Collection $ChartOfAccount
 * @property Doctrine_Collection $ChartOfAccountGroupCode
 * 
 * @method string              getCode()                    Returns the current record's "code" value
 * @method string              getTitle()                   Returns the current record's "title" value
 * @method string              getDescription()             Returns the current record's "description" value
 * @method Doctrine_Collection getChartOfAccount()          Returns the current record's "ChartOfAccount" collection
 * @method Doctrine_Collection getChartOfAccountGroupCode() Returns the current record's "ChartOfAccountGroupCode" collection
 * @method GroupCode           setCode()                    Sets the current record's "code" value
 * @method GroupCode           setTitle()                   Sets the current record's "title" value
 * @method GroupCode           setDescription()             Sets the current record's "description" value
 * @method GroupCode           setChartOfAccount()          Sets the current record's "ChartOfAccount" collection
 * @method GroupCode           setChartOfAccountGroupCode() Sets the current record's "ChartOfAccountGroupCode" collection
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroupCode extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('group_code');
        $this->hasColumn('code', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 60,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ChartOfAccount', array(
             'refClass' => 'ChartOfAccountGroupCode',
             'local' => 'group_code_id',
             'foreign' => 'chart_of_account_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ChartOfAccountGroupCode', array(
             'local' => 'id',
             'foreign' => 'group_code_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}