<?php

/**
 * BaseChartOfAccountType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $title
 * @property string $description
 * @property enum $status
 * @property Doctrine_Collection $Validation
 * @property Doctrine_Collection $ChartOfAccount
 * @property Doctrine_Collection $ChartOfAccountTypeValidation
 * 
 * @method string              getCode()                         Returns the current record's "code" value
 * @method string              getTitle()                        Returns the current record's "title" value
 * @method string              getDescription()                  Returns the current record's "description" value
 * @method enum                getStatus()                       Returns the current record's "status" value
 * @method Doctrine_Collection getValidation()                   Returns the current record's "Validation" collection
 * @method Doctrine_Collection getChartOfAccount()               Returns the current record's "ChartOfAccount" collection
 * @method Doctrine_Collection getChartOfAccountTypeValidation() Returns the current record's "ChartOfAccountTypeValidation" collection
 * @method ChartOfAccountType  setCode()                         Sets the current record's "code" value
 * @method ChartOfAccountType  setTitle()                        Sets the current record's "title" value
 * @method ChartOfAccountType  setDescription()                  Sets the current record's "description" value
 * @method ChartOfAccountType  setStatus()                       Sets the current record's "status" value
 * @method ChartOfAccountType  setValidation()                   Sets the current record's "Validation" collection
 * @method ChartOfAccountType  setChartOfAccount()               Sets the current record's "ChartOfAccount" collection
 * @method ChartOfAccountType  setChartOfAccountTypeValidation() Sets the current record's "ChartOfAccountTypeValidation" collection
 * 
 * @package    Gcross Accounting System
 * @subpackage model
 * @author     Jerick Y. Duguran & Mary Ann I. Altar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChartOfAccountType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chart_of_account_type');
        $this->hasColumn('code', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'default' => '',
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'ACTIVE',
              1 => 'INACTIVE',
             ),
             'default' => 'ACTIVE',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Validation', array(
             'refClass' => 'ChartOfAccountTypeValidation',
             'local' => 'chart_of_account_type_id',
             'foreign' => 'validation_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ChartOfAccount', array(
             'local' => 'id',
             'foreign' => 'chart_of_account_type_id'));

        $this->hasMany('ChartOfAccountTypeValidation', array(
             'local' => 'id',
             'foreign' => 'chart_of_account_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}